[build]
  command = "npm run netlify-build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--legacy-peer-deps" # Helps with dependency resolution
  NETLIFY_NEXT_PLUGIN_SKIP = "true" # Skip the Netlify Next.js plugin since we're using static export
